package com.example.smart_emap.ui.mes.inspection

/** Web の i18n（locales/ja|en|zh|vi.ts の mesInspectionActual）に対応する画面内多言語 */
enum class InspLocale(val glyph: String) {
    Ja("JP"),
    En("EN"),
    Zh("ZH"),
    Vi("VI"),
}

data class InspStrings(
    val title: String,
    val helpOpen: String,
    val productionDay: String,
    val dayPrev: String,
    val dayNext: String,
    val dayToday: String,
    val inspector: String,
    val inspectorPlaceholder: String,
    val selectProduct: String,
    val productPlaceholder: String,
    val btnScanCode: String,
    val scanDialogTitle: String,
    val scanDialogHint: String,
    val scanUseFrontCamera: String,
    val scanUseRearCamera: String,
    val scanRetryCamera: String,
    val scanCameraFailed: String,
    val btnScanDialogClose: String,
    val scanProductInvalidDigits: String,
    val scanProductNotFound: String,
    val scanProductSelected: String,
    val switchProductBlocked: String,
    val sessionLockedByOtherTerminal: String,
    val sessionLockedByOtherTerminalShort: String,
    val sessionResumed: String,
    val sessionRecoveryTitle: String,
    val sessionRecoveryHint: String,
    val btnResumeSession: String,
    val emptySelectProduct: String,
    val inProgressStripTitle: String,
    val defectTotal: String,
    val elapsed: String,
    val pausedAccum: String,
    val timerIdle: String,
    val timerRunning: String,
    val timerPaused: String,
    val timerEnded: String,
    val btnStart: String,
    val btnPause: String,
    val btnResume: String,
    val btnEnd: String,
    val started: String,
    val defectByItem: String,
    val defectHint: String,
    val attributableProcess: String,
    val defectItemsEmpty: String,
    val endDialogTitle: String,
    val endDialogIntro: String,
    val productionQty: String,
    val btnConfirmEnd: String,
    val cancel: String,
    val historyTitle: String,
    val historyProductionQtyTotal: String,
    val productName: String,
    val defectQty: String,
    val defectRate: String,
    val efficiencyRate: String,
)

private val JA = InspStrings(
    title = "検査実績収集",
    helpOpen = "操作説明を開く",
    productionDay = "生産日",
    dayPrev = "前日",
    dayNext = "翌日",
    dayToday = "今日",
    inspector = "検査員",
    inspectorPlaceholder = "検査員を選択",
    selectProduct = "検査製品",
    productPlaceholder = "検査製品を選択",
    btnScanCode = "読取",
    scanDialogTitle = "バーコード / QR 読取",
    scanDialogHint = "枠内にコードを合わせてください。5桁の数字で読取り、検査製品CD（末尾5桁+1）と照合します。",
    scanUseFrontCamera = "前面カメラ",
    scanUseRearCamera = "背面カメラ",
    scanRetryCamera = "カメラを起動",
    scanCameraFailed = "カメラを起動できません。カメラ権限を確認してください。",
    btnScanDialogClose = "閉じる",
    scanProductInvalidDigits = "読取内容は5桁の数字である必要があります",
    scanProductNotFound = "5桁に一致する検査製品がありません",
    scanProductSelected = "検査製品を選択しました",
    switchProductBlocked = "生産中は製品を変更できません。先に生産終了してください。",
    sessionLockedByOtherTerminal = "この検査生産は他の端末で生産中です。当該端末で生産終了してください。",
    sessionLockedByOtherTerminalShort = "他端末生産中",
    sessionResumed = "本端末の操作を再開しました。一時停止・生産終了が可能です。",
    sessionRecoveryTitle = "未終了の検査生産があります",
    sessionRecoveryHint = "「作業を再開」でタイマーと操作を接続してください。",
    btnResumeSession = "作業を再開",
    emptySelectProduct = "検査製品を選択すると作業を開始できます",
    inProgressStripTitle = "検査生産中",
    defectTotal = "不良合計",
    elapsed = "稼働時間",
    pausedAccum = "一時停止",
    timerIdle = "未開始",
    timerRunning = "計測中",
    timerPaused = "一時停止中",
    timerEnded = "終了済",
    btnStart = "生産開始",
    btnPause = "一時停止",
    btnResume = "再開",
    btnEnd = "生産終了",
    started = "生産を開始しました",
    defectByItem = "不良（項目別）",
    defectHint = "生産開始後に +/- で入力",
    attributableProcess = "帰属工程",
    defectItemsEmpty = "不良項目が未登録です",
    endDialogTitle = "生産終了・実績確定",
    endDialogIntro = "内容を確認し、生産数を入力して確定してください。",
    productionQty = "生産数",
    btnConfirmEnd = "実績を確定",
    cancel = "キャンセル",
    historyTitle = "本日の確定実績",
    historyProductionQtyTotal = "生産数合計",
    productName = "製品名",
    defectQty = "不良数",
    defectRate = "不良率",
    efficiencyRate = "能率",
)

private val EN = InspStrings(
    title = "Inspection — actual collection",
    helpOpen = "Open operation manual",
    productionDay = "Production date",
    dayPrev = "Previous day",
    dayNext = "Next day",
    dayToday = "Today",
    inspector = "Inspector",
    inspectorPlaceholder = "Select inspector",
    selectProduct = "Inspection product",
    productPlaceholder = "Select inspection product",
    btnScanCode = "Scan",
    scanDialogTitle = "Barcode / QR scan",
    scanDialogHint = "Align the code in the frame. Scan must be 5 digits; matched to product CD (5 digits + trailing 1).",
    scanUseFrontCamera = "Front camera",
    scanUseRearCamera = "Rear camera",
    scanRetryCamera = "Start camera",
    scanCameraFailed = "Could not start the camera. Check camera permission.",
    btnScanDialogClose = "Close",
    scanProductInvalidDigits = "Scanned value must be exactly 5 digits",
    scanProductNotFound = "No inspection product matches 5-digit code",
    scanProductSelected = "Inspection product selected",
    switchProductBlocked = "Cannot change product while production is in progress. End production first.",
    sessionLockedByOtherTerminal = "This production is active on another device. End it on that device first.",
    sessionLockedByOtherTerminalShort = "Other device",
    sessionResumed = "Resumed control on this device. Pause and end are available.",
    sessionRecoveryTitle = "Unfinished inspection production",
    sessionRecoveryHint = "Tap Resume to reconnect the timer and controls.",
    btnResumeSession = "Resume work",
    emptySelectProduct = "Select an inspection product to start",
    inProgressStripTitle = "In production",
    defectTotal = "Defect total",
    elapsed = "Run time",
    pausedAccum = "Pause total",
    timerIdle = "Not started",
    timerRunning = "Running",
    timerPaused = "Paused",
    timerEnded = "Ended",
    btnStart = "Start",
    btnPause = "Pause",
    btnResume = "Resume",
    btnEnd = "End",
    started = "Production started",
    defectByItem = "Defects by type",
    defectHint = "Use +/- after production start",
    attributableProcess = "Attributable process",
    defectItemsEmpty = "No defect items registered",
    endDialogTitle = "End production — confirm",
    endDialogIntro = "Review the summary, enter production quantity, and confirm.",
    productionQty = "Production qty",
    btnConfirmEnd = "Confirm actuals",
    cancel = "Cancel",
    historyTitle = "Today's confirmed records",
    historyProductionQtyTotal = "Production total",
    productName = "Product name",
    defectQty = "Defect qty",
    defectRate = "Defect rate",
    efficiencyRate = "Efficiency",
)

private val ZH = InspStrings(
    title = "检查实绩收集",
    helpOpen = "打开操作说明",
    productionDay = "生产日期",
    dayPrev = "前一天",
    dayNext = "后一天",
    dayToday = "今天",
    inspector = "检查员",
    inspectorPlaceholder = "当前登录用户",
    selectProduct = "检查产品",
    productPlaceholder = "请选择检查产品",
    btnScanCode = "读取",
    scanDialogTitle = "条形码 / QR 扫描",
    scanDialogHint = "将码对准框内。须为5位数字，与检查产品CD（末5位+1）匹配。",
    scanUseFrontCamera = "前置摄像头",
    scanUseRearCamera = "后置摄像头",
    scanRetryCamera = "启动摄像头",
    scanCameraFailed = "无法启动摄像头，请检查相机权限。",
    btnScanDialogClose = "关闭",
    scanProductInvalidDigits = "扫描内容必须为5位数字",
    scanProductNotFound = "未找到与5位数字匹配的检查产品",
    scanProductSelected = "已选择检查产品",
    switchProductBlocked = "生产中无法更换产品，请先结束生产。",
    sessionLockedByOtherTerminal = "该检查生产正在其他终端进行，请先在对应终端结束生产。",
    sessionLockedByOtherTerminalShort = "其他终端生产中",
    sessionResumed = "已在本终端恢复操作，可暂停和结束生产。",
    sessionRecoveryTitle = "存在未结束的检查生产",
    sessionRecoveryHint = "请点击「继续作业」连接计时器和操作。",
    btnResumeSession = "继续作业",
    emptySelectProduct = "选择检查产品后即可开始作业",
    inProgressStripTitle = "检查生产中",
    defectTotal = "不良合计",
    elapsed = "稼动时间",
    pausedAccum = "暂停累计",
    timerIdle = "未开始",
    timerRunning = "计时中",
    timerPaused = "已暂停",
    timerEnded = "已结束",
    btnStart = "生产开始",
    btnPause = "暂时停止",
    btnResume = "继续",
    btnEnd = "生产结束",
    started = "已开始生产",
    defectByItem = "不良（分项）",
    defectHint = "开始生产后用 +/- 录入",
    attributableProcess = "归属工程",
    defectItemsEmpty = "未登记不良项目",
    endDialogTitle = "生产结束·确定实绩",
    endDialogIntro = "请确认以下内容并输入生产数量后确定。",
    productionQty = "生产数量",
    btnConfirmEnd = "确定实绩",
    cancel = "取消",
    historyTitle = "当日已确定实绩",
    historyProductionQtyTotal = "生产数合计",
    productName = "产品名称",
    defectQty = "不良数",
    defectRate = "不良率",
    efficiencyRate = "能率",
)

private val VI = InspStrings(
    title = "Thu thập thực tế kiểm tra",
    helpOpen = "Mở hướng dẫn vận hành",
    productionDay = "Ngày sản xuất",
    dayPrev = "Ngày trước",
    dayNext = "Ngày sau",
    dayToday = "Hôm nay",
    inspector = "Người kiểm tra",
    inspectorPlaceholder = "Chọn người kiểm tra",
    selectProduct = "Sản phẩm kiểm tra",
    productPlaceholder = "Chọn sản phẩm kiểm tra",
    btnScanCode = "Đọc",
    scanDialogTitle = "Quét mã vạch / QR",
    scanDialogHint = "Căn mã trong khung. Phải đúng 5 chữ số; khớp CD sản phẩm kiểm tra (5 số + hậu tố 1).",
    scanUseFrontCamera = "Camera trước",
    scanUseRearCamera = "Camera sau",
    scanRetryCamera = "Bật camera",
    scanCameraFailed = "Không bật được camera. Kiểm tra quyền camera.",
    btnScanDialogClose = "Đóng",
    scanProductInvalidDigits = "Mã quét phải đúng 5 chữ số",
    scanProductNotFound = "Không có sản phẩm kiểm tra khớp 5 chữ số",
    scanProductSelected = "Đã chọn sản phẩm kiểm tra",
    switchProductBlocked = "Không đổi sản phẩm khi đang sản xuất. Hãy kết thúc trước.",
    sessionLockedByOtherTerminal = "Sản xuất này đang chạy trên thiết bị khác. Hãy kết thúc trên thiết bị đó trước.",
    sessionLockedByOtherTerminalShort = "Thiết bị khác",
    sessionResumed = "Đã tiếp tục điều khiển trên thiết bị này. Có thể tạm dừng và kết thúc.",
    sessionRecoveryTitle = "Còn sản xuất kiểm tra chưa kết thúc",
    sessionRecoveryHint = "Nhấn Tiếp tục để kết nối bộ đếm và thao tác.",
    btnResumeSession = "Tiếp tục công việc",
    emptySelectProduct = "Chọn sản phẩm kiểm tra để bắt đầu",
    inProgressStripTitle = "Đang sản xuất",
    defectTotal = "Tổng lỗi",
    elapsed = "Thời gian chạy",
    pausedAccum = "Tạm dừng",
    timerIdle = "Chưa bắt đầu",
    timerRunning = "Đang đo",
    timerPaused = "Đang tạm dừng",
    timerEnded = "Đã kết thúc",
    btnStart = "Bắt đầu",
    btnPause = "Tạm dừng",
    btnResume = "Tiếp tục",
    btnEnd = "Kết thúc",
    started = "Đã bắt đầu sản xuất",
    defectByItem = "Lỗi theo hạng mục",
    defectHint = "Dùng +/- sau khi bắt đầu sản xuất",
    attributableProcess = "Công đoạn thuộc",
    defectItemsEmpty = "Chưa đăng ký hạng mục lỗi",
    endDialogTitle = "Kết thúc — xác nhận",
    endDialogIntro = "Kiểm tra nội dung, nhập số lượng sản xuất và xác nhận.",
    productionQty = "Số lượng SX",
    btnConfirmEnd = "Xác nhận thực tế",
    cancel = "Hủy",
    historyTitle = "Thực tế đã xác nhận hôm nay",
    historyProductionQtyTotal = "Tổng số lượng SX",
    productName = "Tên sản phẩm",
    defectQty = "Số lỗi",
    defectRate = "Tỷ lệ lỗi",
    efficiencyRate = "Năng suất",
)

fun inspStringsFor(locale: InspLocale): InspStrings = when (locale) {
    InspLocale.Ja -> JA
    InspLocale.En -> EN
    InspLocale.Zh -> ZH
    InspLocale.Vi -> VI
}
