package com.example.smart_emap.ui.mes.chamfering

import com.example.smart_emap.core.network.NetworkErrorHints

enum class ChamferLocale(val glyph: String) {
    Ja("JP"),
    En("EN"),
    Zh("中"),
    Vi("VI"),
}

data class ChamferStrings(
    val title: String,
    val productionDay: String,
    val dayPrev: String,
    val dayNext: String,
    val dayToday: String,
    val machine: String,
    val machinePlaceholder: String,
    val loadPlans: String,
    val hideCompleted: String,
    val filterSwitchOn: String,
    val filterSwitchOff: String,
    val operator: String,
    val operatorPlaceholder: String,
    val setupTime: String,
    val setupTimeUnit: String,
    val sawBladeExchange: String,
    val repairTime: String,
    val plannedQty: String,
    val actualQty: String,
    val mgmtCodeShort: String,
    val seq: String,
    val elapsed: String,
    val pausedAccum: String,
    val btnStart: String,
    val btnPause: String,
    val btnResume: String,
    val btnEnd: String,
    val timerIdle: String,
    val timerRunning: String,
    val timerPaused: String,
    val timerEnded: String,
    val btnScanCode: String,
    val btnEditConfirmed: String,
    val btnChangeMachine: String,
    val moveUp: String,
    val moveDown: String,
    val cmConfirmed: String,
    val cmPending: String,
    val anchorDayBadge: String,
    val planLinesSuffix: String,
    val emptySelectMachine: String,
    val emptyNoPlans: String,
    val loadMachinesFailed: String,
    val loadPlansFailed: String,
    val loadUsersFailed: String,
    val saveFailed: String,
    val completeSaved: String,
    val offlineBanner: String,
    val offlineQueued: String,
    val offlinePendingSync: String,
    val offlineSyncOk: String,
    val offlineListCached: String,
    val needOnlineForEnd: String,
    val singleMachineProductionOnly: String,
    val stateRestored: String,
    val endDialogTitle: String,
    val endDialogQtyLabel: String,
    val endDialogQtyPlaceholder: String,
    val endDialogOperatorMissing: String,
    val endDialogSetupTimeMissing: String,
    val endDialogMetaMissingHint: String,
    val btnCompleteFull: String,
    val btnDefer: String,
    val btnCompleteWithInput: String,
    val qtyInvalid: String,
    val deferQtyMustBeLess: String,
    val deferNextDayLabel: String,
    val deferNextDayRequired: String,
    val deferSubsequentLabel: String,
    val deferQtyDialogTitle: String,
    val deferQtyDialogBaselineLabel: String,
    val deferQtyDialogActualLabel: String,
    val deferQtyDialogRemainderLabel: String,
    val deferQtyDialogDeferToLabel: String,
    val deferConfirmTitle: String,
    val deferConfirmMessage: String,
    val deferSavedWithDate: String,
    val deferSavedWithFollowing: String,
    val btnDeferConfirm: String,
    val btnCancel: String,
    val confirmedEditDialogTitle: String,
    val btnSaveConfirmed: String,
    val confirmedEditSaved: String,
    val productionStart: String,
    val productionEnd: String,
    val confirmedEditPauseHint: String,
    val editTimeRequired: String,
    val editTimeOrder: String,
    val editPauseTooLong: String,
    val needOnlineForConfirmedEdit: String,
    val changeMachineDialogTitle: String,
    val btnChangeMachineSave: String,
    val changeMachineSaved: String,
    val reorderSaved: String,
    val reorderFailed: String,
    val dragToReorder: String,
    val needOnlineForEdit: String,
    val scanSaved: String,
    val scanRegistered: String,
    val invalidProductionDay: String,
    val emptyMachineName: String,
    val networkSslError: String,
    val networkConnectionError: String,
    val networkTimeoutError: String,
    val networkServerError: String,
    val networkNoConnectionError: String,
)

private val JA = ChamferStrings(
    title = "面取実績収集",
    productionDay = "生産日",
    dayPrev = "前日",
    dayNext = "翌日",
    dayToday = "今日",
    machine = "面取設備",
    machinePlaceholder = "設備を選択",
    loadPlans = "面取指示を取得",
    hideCompleted = "実績確定済",
    filterSwitchOn = "除く",
    filterSwitchOff = "全件",
    operator = "作業者",
    operatorPlaceholder = "作業者を選択",
    setupTime = "段取時間",
    setupTimeUnit = "分",
    sawBladeExchange = "鋸刃交換",
    repairTime = "修理",
    plannedQty = "計画数",
    actualQty = "実績数",
    mgmtCodeShort = "コード {code}",
    seq = "順",
    elapsed = "稼働計測",
    pausedAccum = "一時停止累計",
    btnStart = "生産開始",
    btnPause = "一時停止",
    btnResume = "再開",
    btnEnd = "生産終了",
    timerIdle = "未開始",
    timerRunning = "計測中",
    timerPaused = "一時停止中",
    timerEnded = "終了済",
    btnScanCode = "読取",
    btnEditConfirmed = "編集",
    btnChangeMachine = "設備変更",
    moveUp = "上へ",
    moveDown = "下へ",
    cmConfirmed = "実績確定済",
    cmPending = "未確定",
    anchorDayBadge = "選択日",
    planLinesSuffix = "件",
    emptySelectMachine = "面取設備を選択して「面取指示を取得」を押してください。",
    emptyNoPlans = "この条件の面取指示はありません。",
    loadMachinesFailed = "面取設備一覧の取得に失敗しました。",
    loadPlansFailed = "面取指示の取得に失敗しました。",
    loadUsersFailed = "ユーザー一覧の取得に失敗しました。",
    saveFailed = "保存に失敗しました",
    completeSaved = "実績を確定しました",
    offlineBanner = "オフラインです。計測は継続でき、変更は端末に保存されます。",
    offlineQueued = "サーバーに未送信のため端末に保存しました。",
    offlinePendingSync = "未同期 {n} 件。接続中に自動送信します…",
    offlineSyncOk = "{n} 件をサーバーに同期しました。",
    offlineListCached = "一覧の取得に失敗しました。前回表示分と端末の計測状態で作業を続けられます。",
    needOnlineForEnd = "生産終了・順延はオンライン時のみ実行できます。",
    singleMachineProductionOnly = "この面取機では他の製品が生産中です（{label}）。先に生産終了してください。",
    stateRestored = "前回の画面状態を復元しました。",
    endDialogTitle = "生産終了・実績本数",
    endDialogQtyLabel = "本日生産実績数（順延時は当日できあがり本数）",
    endDialogQtyPlaceholder = "実績本数を入力",
    endDialogOperatorMissing = "未入力",
    endDialogSetupTimeMissing = "未入力",
    endDialogMetaMissingHint = "作業者または段取時間が未入力です。一覧画面で入力してから確定してください。",
    btnCompleteFull = "この {n} 本で完了（満了）",
    btnDefer = "生産順延",
    btnCompleteWithInput = "入力実績で完了",
    qtyInvalid = "実績数を正しく入力してください",
    deferQtyMustBeLess = "順延時は実績を指示本数未満にしてください",
    deferNextDayLabel = "順延先の生産日",
    deferNextDayRequired = "順延先の生産日を選択してください",
    deferSubsequentLabel = "この行より後の計画 {n} 件の生産日を順延先と同じ日に変更（数量分割なし）",
    deferQtyDialogTitle = "生産実績数の入力",
    deferQtyDialogBaselineLabel = "指示本数",
    deferQtyDialogActualLabel = "本日生産実績数",
    deferQtyDialogRemainderLabel = "順延本数",
    deferQtyDialogDeferToLabel = "順延先: {date}",
    deferConfirmTitle = "生産順延の確認",
    deferConfirmMessage = "順延先: {date}。当日 {remainder} 本を順延します。よろしいですか？",
    deferSavedWithDate = "順延しました（順延先: {date}）",
    deferSavedWithFollowing = "{n} 件を順延しました（順延先: {date}）",
    btnDeferConfirm = "確認して順延",
    btnCancel = "取消",
    confirmedEditDialogTitle = "実績確定済の修正",
    btnSaveConfirmed = "保存",
    confirmedEditSaved = "実績確定済データを更新しました",
    productionStart = "生産開始",
    productionEnd = "生産終了",
    confirmedEditPauseHint = "一時停止累計は秒単位。稼働は開始・終了・停止から自動計算されます。",
    editTimeRequired = "生産開始・終了の日時を入力してください",
    editTimeOrder = "終了は開始より後にしてください",
    editPauseTooLong = "一時停止累計が生産時間を超えています",
    needOnlineForConfirmedEdit = "実績確定済の修正はオンライン時のみ実行できます。",
    changeMachineDialogTitle = "面取設備の変更",
    btnChangeMachineSave = "設備を変更",
    changeMachineSaved = "設備を変更しました: {machine}",
    reorderSaved = "生産順を更新しました",
    reorderFailed = "生産順の更新に失敗しました",
    dragToReorder = "カードを2秒長押ししてドラッグで順序変更",
    needOnlineForEdit = "順序変更はオンライン時のみ実行できます。",
    scanSaved = "読取コードを保存しました",
    scanRegistered = "管理コードと一致しました",
    invalidProductionDay = "生産日が不正です。",
    emptyMachineName = "選択した設備に面取機名がありません。",
    networkSslError = "SSL証明書エラー",
    networkConnectionError = "接続エラー",
    networkTimeoutError = "タイムアウト",
    networkServerError = "サーバーエラー",
    networkNoConnectionError = "ネットワーク未接続",
)

private val EN = JA.copy(
    title = "Chamfering actual collection",
    productionDay = "Production day",
    dayPrev = "Prev",
    dayNext = "Next",
    dayToday = "Today",
    machine = "Chamfering machine",
    machinePlaceholder = "Select machine",
    loadPlans = "Load chamfering plans",
    hideCompleted = "Hide confirmed",
    filterSwitchOn = "Hide",
    filterSwitchOff = "All",
    operator = "Operator",
    operatorPlaceholder = "Select operator",
    setupTime = "Setup time",
    setupTimeUnit = "min",
    sawBladeExchange = "Saw blade",
    repairTime = "Repair",
    plannedQty = "Planned",
    actualQty = "Actual",
    seq = "Seq",
    elapsed = "Run time",
    pausedAccum = "Paused total",
    btnStart = "Start",
    btnPause = "Pause",
    btnResume = "Resume",
    btnEnd = "End",
    timerIdle = "Idle",
    timerRunning = "Running",
    timerPaused = "Paused",
    timerEnded = "Ended",
    btnScanCode = "Scan",
    btnEditConfirmed = "Edit",
    btnChangeMachine = "Change machine",
    moveUp = "Up",
    moveDown = "Down",
    cmConfirmed = "Confirmed",
    cmPending = "Pending",
    anchorDayBadge = "Selected",
    planLinesSuffix = "lines",
    emptySelectMachine = "Select a chamfering machine and tap Load chamfering plans.",
    emptyNoPlans = "No chamfering plans for this filter.",
    loadMachinesFailed = "Failed to load machines.",
    loadPlansFailed = "Failed to load chamfering plans.",
    loadUsersFailed = "Failed to load users.",
    saveFailed = "Save failed",
    completeSaved = "Production completed",
    offlineBanner = "Offline. Timing continues; changes are saved on device.",
    offlineQueued = "Saved on device (not sent yet).",
    offlinePendingSync = "{n} pending sync…",
    offlineSyncOk = "Synced {n} item(s).",
    offlineListCached = "Could not load the list. Continue with the last shown data and local timers.",
    needOnlineForEnd = "End production and defer require online connection.",
    singleMachineProductionOnly = "Another product is in progress ({label}). End it first.",
    stateRestored = "Restored previous screen state.",
    endDialogTitle = "End production · quantity",
    endDialogQtyLabel = "Today's actual qty (finished today when deferring)",
    endDialogQtyPlaceholder = "Enter actual qty",
    endDialogOperatorMissing = "Not entered",
    endDialogSetupTimeMissing = "Not entered",
    endDialogMetaMissingHint = "Operator or setup time is missing.",
    btnCompleteFull = "Complete with {n} pcs (full)",
    btnDefer = "Defer remainder",
    btnCompleteWithInput = "Complete with input",
    qtyInvalid = "Enter a valid quantity",
    deferQtyMustBeLess = "For defer, qty must be less than instruction qty",
    deferNextDayLabel = "Defer to day",
    deferNextDayRequired = "Select a defer target day",
    deferSubsequentLabel = "Move {n} plan(s) after this row to the same defer day (no qty split)",
    deferQtyDialogTitle = "Enter actual quantity",
    deferQtyDialogBaselineLabel = "Instruction qty",
    deferQtyDialogActualLabel = "Today's actual qty",
    deferQtyDialogRemainderLabel = "Defer qty",
    deferQtyDialogDeferToLabel = "Defer to: {date}",
    deferConfirmTitle = "Confirm defer",
    deferConfirmMessage = "Defer to {date}. Move {remainder} pcs. Continue?",
    deferSavedWithDate = "Deferred (target: {date})",
    deferSavedWithFollowing = "Deferred {n} item(s) (target: {date})",
    btnDeferConfirm = "Confirm defer",
    btnCancel = "Cancel",
    confirmedEditDialogTitle = "Edit confirmed actual",
    btnSaveConfirmed = "Save",
    confirmedEditSaved = "Confirmed actual updated",
    productionStart = "Start",
    productionEnd = "End",
    confirmedEditPauseHint = "Pause total is in seconds. Run time is derived from start, end, and pause.",
    editTimeRequired = "Enter production start and end times",
    editTimeOrder = "End time must be after start time",
    editPauseTooLong = "Pause total exceeds production duration",
    needOnlineForConfirmedEdit = "Editing confirmed actuals requires an online connection.",
    changeMachineDialogTitle = "Change chamfering machine",
    btnChangeMachineSave = "Save machine",
    changeMachineSaved = "Machine changed: {machine}",
    reorderSaved = "Sequence updated",
    reorderFailed = "Failed to update sequence",
    dragToReorder = "Long press card for 2s, then drag to reorder",
    needOnlineForEdit = "Reordering requires an online connection.",
    scanSaved = "Scan code saved",
    scanRegistered = "Matches management code",
    invalidProductionDay = "Invalid production day.",
    emptyMachineName = "Selected machine has no name.",
    networkSslError = "SSL certificate error",
    networkConnectionError = "Connection error",
    networkTimeoutError = "Timeout",
    networkServerError = "Server error",
    networkNoConnectionError = "No network",
)

private val ZH = JA.copy(
    title = "面取实绩收集",
    productionDay = "生产日",
    dayPrev = "前一天",
    dayNext = "后一天",
    dayToday = "今天",
    machine = "面取设备",
    machinePlaceholder = "选择设备",
    loadPlans = "获取面取指示",
    hideCompleted = "隐藏已确定",
    filterSwitchOn = "排除",
    filterSwitchOff = "全部",
    operator = "作业者",
    operatorPlaceholder = "选择作业者",
    setupTime = "段取时间",
    setupTimeUnit = "分",
    sawBladeExchange = "锯刃更换",
    repairTime = "修理",
    plannedQty = "计划数",
    actualQty = "实绩数",
    seq = "顺序",
    elapsed = "稼动计时",
    pausedAccum = "暂停累计",
    btnStart = "生产开始",
    btnPause = "暂停",
    btnResume = "继续",
    btnEnd = "生产结束",
    timerIdle = "未开始",
    timerRunning = "计时中",
    timerPaused = "暂停中",
    timerEnded = "已结束",
    btnScanCode = "扫码",
    btnEditConfirmed = "编辑",
    btnChangeMachine = "变更设备",
    moveUp = "上移",
    moveDown = "下移",
    cmConfirmed = "实绩已确定",
    cmPending = "未确定",
    anchorDayBadge = "选择日",
    planLinesSuffix = "条",
    emptySelectMachine = "请选择面取设备并点击获取面取指示。",
    emptyNoPlans = "没有符合条件的面取指示。",
    loadMachinesFailed = "获取面取设备失败。",
    loadPlansFailed = "获取面取指示失败。",
    loadUsersFailed = "获取用户列表失败。",
    saveFailed = "保存失败",
    completeSaved = "实绩已确定",
    offlineBanner = "离线中。计测继续，变更保存在本机。",
    offlineQueued = "未发送，已保存在本机。",
    offlinePendingSync = "未同步 {n} 条…",
    offlineSyncOk = "已同步 {n} 条。",
    offlineListCached = "列表获取失败，可基于上次显示的数据与本地计测继续作业。",
    needOnlineForEnd = "生产结束和顺延需在线。",
    singleMachineProductionOnly = "该面取机有其他产品生产中（{label}）。请先结束。",
    stateRestored = "已恢复上次画面状态。",
    endDialogTitle = "生产结束·实绩本数",
    endDialogQtyLabel = "本日生产实绩数（顺延时为当日完成本数）",
    endDialogQtyPlaceholder = "输入实绩本数",
    endDialogOperatorMissing = "未输入",
    endDialogSetupTimeMissing = "未输入",
    endDialogMetaMissingHint = "作业者或段取时间未填写。",
    btnCompleteFull = "以 {n} 本完成（满量）",
    btnDefer = "生产顺延",
    btnCompleteWithInput = "按输入实绩完成",
    qtyInvalid = "请输入正确的实绩数",
    deferQtyMustBeLess = "顺延时实绩须小于指示本数",
    deferNextDayLabel = "顺延目标生产日",
    deferNextDayRequired = "请选择顺延目标生产日",
    deferSubsequentLabel = "将此行之后 {n} 条计划的生产日改为同一顺延日（不分割数量）",
    deferQtyDialogTitle = "输入生产实绩数",
    deferQtyDialogBaselineLabel = "指示本数",
    deferQtyDialogActualLabel = "本日生产实绩数",
    deferQtyDialogRemainderLabel = "顺延本数",
    deferQtyDialogDeferToLabel = "顺延至: {date}",
    deferConfirmTitle = "确认生产顺延",
    deferConfirmMessage = "顺延至 {date}，移动 {remainder} 本。确定？",
    deferSavedWithDate = "已顺延（目标日: {date}）",
    deferSavedWithFollowing = "已顺延 {n} 条（目标日: {date}）",
    btnDeferConfirm = "确认顺延",
    btnCancel = "取消",
    confirmedEditDialogTitle = "修改已确定实绩",
    btnSaveConfirmed = "保存",
    confirmedEditSaved = "已更新确定实绩",
    productionStart = "开始时间",
    productionEnd = "结束时间",
    confirmedEditPauseHint = "暂停累计单位为秒。稼动时间由开始、结束与暂停自动计算。",
    editTimeRequired = "请输入生产开始与结束时间",
    editTimeOrder = "结束时间须晚于开始时间",
    editPauseTooLong = "暂停累计超过生产时长",
    needOnlineForConfirmedEdit = "修改已确定实绩需在线。",
    changeMachineDialogTitle = "变更面取设备",
    btnChangeMachineSave = "保存设备",
    changeMachineSaved = "设备已变更: {machine}",
    reorderSaved = "生产顺序已更新",
    reorderFailed = "更新生产顺序失败",
    dragToReorder = "长按卡片2秒后拖动调整顺序",
    needOnlineForEdit = "调整顺序需在线。",
    scanSaved = "读码已保存",
    scanRegistered = "与管理代码一致",
    invalidProductionDay = "生产日无效。",
    emptyMachineName = "所选设备无面取机名称。",
    networkSslError = "SSL证书错误",
    networkConnectionError = "连接错误",
    networkTimeoutError = "超时",
    networkServerError = "服务器错误",
    networkNoConnectionError = "无网络连接",
)

private val VI = JA.copy(
    title = "Thu thập thực tế vát",
    productionDay = "Ngày sản xuất",
    dayPrev = "Trước",
    dayNext = "Sau",
    dayToday = "Hôm nay",
    machine = "Máy vát",
    machinePlaceholder = "Chọn máy",
    loadPlans = "Tải kế hoạch vát",
    hideCompleted = "Ẩn đã xác nhận",
    filterSwitchOn = "Loại",
    filterSwitchOff = "Tất cả",
    operator = "Người vận hành",
    operatorPlaceholder = "Chọn người vận hành",
    setupTime = "Thời gian setup",
    setupTimeUnit = "phút",
    sawBladeExchange = "Đổi lưỡi cưa",
    repairTime = "Sửa chữa",
    plannedQty = "Kế hoạch",
    actualQty = "Thực tế",
    seq = "TT",
    elapsed = "Thời gian chạy",
    pausedAccum = "Tạm dừng tích lũy",
    btnStart = "Bắt đầu",
    btnPause = "Tạm dừng",
    btnResume = "Tiếp tục",
    btnEnd = "Kết thúc",
    timerIdle = "Chưa bắt đầu",
    timerRunning = "Đang đo",
    timerPaused = "Đang tạm dừng",
    timerEnded = "Đã kết thúc",
    btnScanCode = "Quét mã",
    btnEditConfirmed = "Sửa",
    btnChangeMachine = "Đổi máy",
    moveUp = "Lên",
    moveDown = "Xuống",
    cmConfirmed = "Đã xác nhận",
    cmPending = "Chưa xác nhận",
    anchorDayBadge = "Ngày chọn",
    planLinesSuffix = "dòng",
    emptySelectMachine = "Chọn máy cắt và nhấn Tải kế hoạch cắt.",
    emptyNoPlans = "Không có kế hoạch cắt phù hợp.",
    loadMachinesFailed = "Không tải được danh sách máy.",
    loadPlansFailed = "Không tải được kế hoạch cắt.",
    loadUsersFailed = "Không tải được danh sách người dùng.",
    saveFailed = "Lưu thất bại",
    completeSaved = "Đã xác nhận thực tế",
    offlineBanner = "Ngoại tuyến. Đo thời gian tiếp tục; thay đổi lưu trên thiết bị.",
    offlineQueued = "Đã lưu trên thiết bị (chưa gửi).",
    offlinePendingSync = "Chưa đồng bộ {n} mục…",
    offlineSyncOk = "Đã đồng bộ {n} mục.",
    offlineListCached = "Không tải được danh sách. Tiếp tục với dữ liệu lần trước và bộ đếm cục bộ.",
    needOnlineForEnd = "Kết thúc và hoãn cần kết nối mạng.",
    singleMachineProductionOnly = "Máy đang sản xuất sản phẩm khác ({label}). Kết thúc trước.",
    stateRestored = "Đã khôi phục trạng thái màn hình.",
    endDialogTitle = "Kết thúc · số lượng",
    endDialogQtyLabel = "Số lượng thực tế hôm nay (khi hoãn: số hoàn thành trong ngày)",
    endDialogQtyPlaceholder = "Nhập số lượng",
    endDialogOperatorMissing = "Chưa nhập",
    endDialogSetupTimeMissing = "Chưa nhập",
    endDialogMetaMissingHint = "Thiếu người vận hành hoặc thời gian setup.",
    btnCompleteFull = "Hoàn thành {n} pcs (đủ)",
    btnDefer = "Hoãn phần còn lại",
    btnCompleteWithInput = "Hoàn thành theo nhập",
    qtyInvalid = "Nhập số lượng hợp lệ",
    deferQtyMustBeLess = "Khi hoãn, số lượng phải nhỏ hơn chỉ thị",
    deferNextDayLabel = "Ngày hoãn đến",
    deferNextDayRequired = "Chọn ngày hoãn đích",
    deferSubsequentLabel = "Chuyển {n} kế hoạch sau dòng này sang cùng ngày hoãn (không tách số lượng)",
    deferQtyDialogTitle = "Nhập số lượng thực tế",
    deferQtyDialogBaselineLabel = "Số lượng chỉ thị",
    deferQtyDialogActualLabel = "SL thực tế hôm nay",
    deferQtyDialogRemainderLabel = "SL hoãn",
    deferQtyDialogDeferToLabel = "Hoãn đến: {date}",
    deferConfirmTitle = "Xác nhận hoãn",
    deferConfirmMessage = "Hoãn đến {date}, chuyển {remainder} pcs. Tiếp tục?",
    deferSavedWithDate = "Đã hoãn (đích: {date})",
    deferSavedWithFollowing = "Đã hoãn {n} mục (đích: {date})",
    btnDeferConfirm = "Xác nhận hoãn",
    btnCancel = "Hủy",
    confirmedEditDialogTitle = "Sửa thực tế đã xác nhận",
    btnSaveConfirmed = "Lưu",
    confirmedEditSaved = "Đã cập nhật thực tế xác nhận",
    productionStart = "Bắt đầu",
    productionEnd = "Kết thúc",
    confirmedEditPauseHint = "Tổng tạm dừng tính bằng giây. Thời gian chạy được tính từ bắt đầu, kết thúc và tạm dừng.",
    editTimeRequired = "Nhập thời gian bắt đầu và kết thúc sản xuất",
    editTimeOrder = "Thời gian kết thúc phải sau thời gian bắt đầu",
    editPauseTooLong = "Tổng tạm dừng vượt quá thời gian sản xuất",
    needOnlineForConfirmedEdit = "Sửa thực tế đã xác nhận cần kết nối mạng.",
    changeMachineDialogTitle = "Đổi máy vát",
    btnChangeMachineSave = "Lưu máy",
    changeMachineSaved = "Đã đổi máy: {machine}",
    reorderSaved = "Đã cập nhật thứ tự",
    reorderFailed = "Cập nhật thứ tự thất bại",
    dragToReorder = "Nhấn giữ thẻ 2 giây rồi kéo để đổi thứ tự",
    needOnlineForEdit = "Đổi thứ tự cần kết nối mạng.",
    scanSaved = "Đã lưu mã quét",
    scanRegistered = "Khớp mã quản lý",
    invalidProductionDay = "Ngày sản xuất không hợp lệ.",
    emptyMachineName = "Máy đã chọn không có tên.",
    networkSslError = "Lỗi chứng chỉ SSL",
    networkConnectionError = "Lỗi kết nối",
    networkTimeoutError = "Hết thời gian",
    networkServerError = "Lỗi máy chủ",
    networkNoConnectionError = "Không có mạng",
)

fun ChamferStrings.networkErrorHints(): NetworkErrorHints = NetworkErrorHints(
    ssl = networkSslError,
    connection = networkConnectionError,
    timeout = networkTimeoutError,
    server = networkServerError,
    noConnection = networkNoConnectionError,
)

fun chamferStringsFor(locale: ChamferLocale): ChamferStrings = when (locale) {
    ChamferLocale.Ja -> JA
    ChamferLocale.En -> EN
    ChamferLocale.Zh -> ZH
    ChamferLocale.Vi -> VI
}

fun ChamferStrings.format(template: String, vararg pairs: Pair<String, Any>): String {
    var out = template
    for ((k, v) in pairs) out = out.replace("{$k}", v.toString())
    return out
}
