package com.example.smart_emap.ui.mes.planinstruction

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

object PlanInstructionTheme {
    val PageBgStart = Color(0xFFF8FAFC)
    val PageBgEnd = Color(0xFFF1F5F9)
    val CardBg = Color(0xFFFAFBFC)
    val CardBorder = Color(0x66E2E8F0)
    val CardShadow = Color(0x1A0F172A)
    val TitleDark = Color(0xFF1E293B)
    val Subtitle = Color(0xFF64748B)
    val FilterLabel = Color(0xFF334155)
    val TableBorder = Color(0xFFE2E8F0)
    val TableHeaderBg = Color(0xFFF8FAFC)
    val TableStripeBg = Color(0xFFF9FAFB)
    val FilterBorder = Color(0xFFCBD5E1)
    val FilterBg = Color(0xFFF8FAFC)
    val SearchBarBgStart = Color(0xFFE8F0FE)
    val SearchBarBgEnd = Color(0xFFF5F0FF)
    val SearchBarBorderStart = Color(0xFFBFDBFE)
    val SearchBarBorderEnd = Color(0xFFDDD6FE)
    val ToolbarFieldTop = Color(0xFFFFFFFF)
    val ToolbarFieldBottom = Color(0xFFF1F5F9)
    val ToolbarFieldShadow = Color(0x332563EB)
    val ToolbarLabelAccent = Color(0xFF06B6D4)
    val ToolbarLabelBgStart = Color(0xFFECFEFF)
    val ToolbarLabelBgEnd = Color(0xFFCFFAFE)
    val ToolbarLabelText = Color(0xFF0E7490)
    val HighlightRowBg = Color(0xFFFFFDE7)
    val NotesBadge = Color(0xFFEF4444)

    val StatTotalGradient = Brush.linearGradient(listOf(Color(0xFF667EEA), Color(0xFF764BA2)))
    val StatMachineGradient = Brush.linearGradient(listOf(Color(0xFFF093FB), Color(0xFFF5576C)))
    val HeaderTopGradient = Brush.horizontalGradient(listOf(Color(0xFF3B82F6), Color(0xFF8B5CF6), Color(0xFFEC4899)))
    val TitleGradient = Brush.linearGradient(listOf(Color(0xFF1E293B), Color(0xFF3B82F6)))

    val DatePrevGradient = Brush.linearGradient(listOf(Color(0xFFF97373), Color(0xFFDC2626)))
    val DateTodayGradient = Brush.linearGradient(listOf(Color(0xFF60A5FA), Color(0xFF2563EB)))
    val DateNextGradient = Brush.linearGradient(listOf(Color(0xFF34D399), Color(0xFF059669)))
    val BtnIssueGradient = Brush.linearGradient(listOf(Color(0xFF22C55E), Color(0xFF15803D)))
    val BtnPrimaryGradient = Brush.linearGradient(listOf(Color(0xFF6366F1), Color(0xFF4338CA)))
    val BtnRefreshGradient = Brush.linearGradient(listOf(Color(0xFF64748B), Color(0xFF334155)))
    val NotesBtnGradient = Brush.linearGradient(listOf(Color(0xFFF5F3FF), Color(0xFFEDE9FE)))
    val NotesBtnBorder = Color(0xFFDDD6FE)
    val NotesBtnText = Color(0xFF5B21B6)

    val ChartPlanPast = Brush.verticalGradient(listOf(Color(0xFFBAE6FD), Color(0xFF0284C7)))
    val ChartPlanToday = Brush.verticalGradient(listOf(Color(0xFF6EE7B7), Color(0xFF047857)))
    val ChartPlanFuture = Brush.verticalGradient(listOf(Color(0xFFF1F5F9), Color(0xFF94A3B8)))
    val ChartActualPast = Brush.verticalGradient(listOf(Color(0xFFFDE68A), Color(0xFFD97706)))
    val ChartActualToday = Brush.verticalGradient(listOf(Color(0xFFFCD34D), Color(0xFFB45309)))
    val ChartActualFuture = Brush.verticalGradient(listOf(Color(0xFFFEF3C7), Color(0xFFD6D3D1)))
    val ChartTodayLine = Color(0xFFF59E0B)

    val NotesDialogBorder = Color(0xFFDDD6FE)
    val NotesDialogHeaderStart = Color(0xFFF5F3FF)
    val NotesDialogHeaderMid = Color(0xFFEEF2FF)
    val NotesDialogHeaderEnd = Color(0xFFECFEFF)
    val NotesDialogTitle = Color(0xFF5B21B6)
    val NotesDialogBodyTop = Color(0xFFFAFAFF)
    val NotesDialogBodyBottom = Color(0xFFF8FAFC)
    val NotesDialogFooterBg = Color(0xFFFCFCFF)
    val NotesDialogAddBorder = Color(0xFFE9D5FF)
    val NotesDialogAddBgStart = Color(0xFFFFFFFF)
    val NotesDialogAddBgEnd = Color(0xFFF8F5FF)
    val NotesDialogInputBorder = Color(0xFFE9D5FF)
    val NotesDialogCharCount = Color(0xFF94A3B8)
    val NotesDialogAddBtn = Color(0xFF409EFF)
    val NotesDialogRowBorder = Color(0xFFF3E8FF)
    val NotesDialogRowBg = Color(0xFFFAF5FF)
    val NotesDialogCheckbox = Color(0xFF8B5CF6)
    val NotesDialogDelete = Color(0xFF64748B)
}
