package com.example.smart_emap.ui.mes.welding

import com.example.smart_emap.core.network.NetworkErrorHints

/** Web の i18n（locales/ja|en|zh|vi.ts の mesWeldingActual）に対応する画面内多言語 */
enum class WeldLocale(val glyph: String) {
    Ja("JP"),
    En("EN"),
    Zh("ZH"),
    Vi("VI"),
}

data class WeldStrings(
    val title: String,
    val helpOpen: String,
    val productionDay: String,
    val dayPrev: String,
    val dayNext: String,
    val dayToday: String,
    val inspector: String,
    val inspectorPlaceholder: String,
    val selectProduct: String,
    val productPlaceholder: String,
    val productSearchHint: String,
    val productListEmpty: String,
    val loadProductsFailed: String,
    val loadPlansFailed: String,
    val loadDefectsFailed: String,
    val saveFailed: String,
    val syncStaleBanner: String,
    val syncRecovered: String,
    val btnRetry: String,
    val btnDismiss: String,
    val networkSslError: String,
    val networkConnectionError: String,
    val networkTimeoutError: String,
    val networkServerError: String,
    val networkNoConnectionError: String,
    val offlineModeBanner: String,
    val pendingSyncBanner: String,
    val syncUploadedSuccess: String,
    val endProductionSaved: String,
    val btnScanCode: String,
    val scanDialogTitle: String,
    val scanDialogHint: String,
    val scanUseFrontCamera: String,
    val scanUseRearCamera: String,
    val scanRetryCamera: String,
    val scanCameraFailed: String,
    val btnScanDialogClose: String,
    val scanProductInvalidDigits: String,
    val scanProductNotFound: String,
    val scanProductSelected: String,
    val switchProductBlocked: String,
    val sessionLockedByOtherTerminal: String,
    val sessionLockedByOtherTerminalShort: String,
    val sessionResumed: String,
    val sessionRecoveryTitle: String,
    val sessionRecoveryHint: String,
    val btnResumeSession: String,
    val emptySelectProduct: String,
    val inProgressStripTitle: String,
    val inProgressStripHint: String,
    val switchedToActiveProduction: String,
    val inspectorAlreadyProducing: String,
    val defectTotal: String,
    val elapsed: String,
    val pausedAccum: String,
    val timerIdle: String,
    val timerRunning: String,
    val timerPaused: String,
    val timerEnded: String,
    val btnStart: String,
    val btnPause: String,
    val btnResume: String,
    val btnEnd: String,
    val started: String,
    val defectByItem: String,
    val defectHint: String,
    val attributableProcess: String,
    val defectItemsEmpty: String,
    val endDialogTitle: String,
    val endDialogIntro: String,
    val productionQty: String,
    val btnConfirmEnd: String,
    val cancel: String,
    val historyTitle: String,
    val historyProductionQtyTotal: String,
    val productCd: String,
    val productName: String,
    val defectQty: String,
    val defectRate: String,
    val efficiencyRate: String,
    val productionStart: String,
    val productionEnd: String,
    val dtWheelMonth: String,
    val dtWheelDay: String,
    val dtWheelHour: String,
    val dtWheelMinute: String,
    val elapsedMinutes: String,
    val pausedAccumMinutes: String,
    val historyActions: String,
    val btnEditConfirmed: String,
    val confirmedEditDialogTitle: String,
    val btnSaveConfirmed: String,
    val confirmedEditSaved: String,
    val cannotEditOthersRecord: String,
    val confirmedEditPauseHint: String,
    val editTimeRequired: String,
    val editTimeOrder: String,
    val editPauseTooLong: String,
    val qtyInvalid: String,
    val remarks: String,
)

private val JA = WeldStrings(
    title = "溶接実績収集",
    helpOpen = "操作説明を開く",
    productionDay = "生産日",
    dayPrev = "前日",
    dayNext = "翌日",
    dayToday = "今日",
    inspector = "溶接作業者",
    inspectorPlaceholder = "溶接作業者を選択",
    selectProduct = "溶接製品",
    productPlaceholder = "溶接製品を選択",
    productSearchHint = "品番・品名で検索",
    productListEmpty = "該当する溶接製品がありません",
    loadProductsFailed = "溶接製品一覧の取得に失敗しました",
    loadPlansFailed = "溶接指示一覧の取得に失敗しました",
    loadDefectsFailed = "不良項目の取得に失敗しました",
    saveFailed = "保存に失敗しました",
    syncStaleBanner = "サーバーと同期できません。表示データが最新でない可能性があります。",
    syncRecovered = "サーバーとの同期が回復しました",
    btnRetry = "再読込",
    btnDismiss = "閉じる",
    networkSslError = "SSL接続に失敗しました。サーバーアドレスがバックエンド API（例: http://LAN-IP:8010/）であることを確認してください。",
    networkConnectionError = "サーバーに接続できません。アドレス・ポート・バックエンド起動を確認してください。",
    networkTimeoutError = "接続がタイムアウトしました。ネットワークを確認するか、しばらくして再試行してください。",
    networkServerError = "サーバーが一時的に利用できません。しばらくして再試行してください。",
    networkNoConnectionError = "ネットワークに接続できません。Wi‑Fi またはモバイルデータを確認してください。",
    offlineModeBanner = "オフライン作業中。変更は端末に保存され、接続復旧後に自動アップロードされます。",
    pendingSyncBanner = "同期待ち {count} 件",
    syncUploadedSuccess = "オフライン変更をサーバーにアップロードしました",
    endProductionSaved = "実績を保存しました",
    btnScanCode = "読取",
    scanDialogTitle = "バーコード / QR 読取",
    scanDialogHint = "枠内にコードを合わせてください。5桁の数字で読取り、溶接製品CD（末尾5桁+1）と照合します。",
    scanUseFrontCamera = "前面カメラ",
    scanUseRearCamera = "背面カメラ",
    scanRetryCamera = "カメラを起動",
    scanCameraFailed = "カメラを起動できません。カメラ権限を確認してください。",
    btnScanDialogClose = "閉じる",
    scanProductInvalidDigits = "読取内容は5桁の数字である必要があります",
    scanProductNotFound = "5桁に一致する溶接製品がありません",
    scanProductSelected = "溶接製品を選択しました",
    switchProductBlocked = "生産中は製品を変更できません。先に生産終了してください。",
    sessionLockedByOtherTerminal = "この溶接生産は他の端末で生産中です。当該端末で生産終了してください。",
    sessionLockedByOtherTerminalShort = "他端末生産中",
    sessionResumed = "本端末の操作を再開しました。一時停止・生産終了が可能です。",
    sessionRecoveryTitle = "未終了の溶接生産があります",
    sessionRecoveryHint = "「作業を再開」でタイマーと操作を接続してください。",
    btnResumeSession = "作業を再開",
    emptySelectProduct = "溶接製品を選択すると作業を開始できます",
    inProgressStripTitle = "溶接生産中",
    inProgressStripHint = "別の製品を選択中です。作業を再開するか、先に生産終了してください。",
    switchedToActiveProduction = "生産中の製品（{label}）に切り替えました",
    inspectorAlreadyProducing = "この溶接作業者は別製品を生産中です（{label}）。先に生産終了してください。",
    defectTotal = "不良合計",
    elapsed = "稼働時間",
    pausedAccum = "一時停止",
    timerIdle = "未開始",
    timerRunning = "計測中",
    timerPaused = "一時停止中",
    timerEnded = "終了済",
    btnStart = "生産開始",
    btnPause = "一時停止",
    btnResume = "再開",
    btnEnd = "生産終了",
    started = "生産を開始しました",
    defectByItem = "不良（項目別）",
    defectHint = "生産開始後に +/- で入力",
    attributableProcess = "帰属工程",
    defectItemsEmpty = "不良項目が未登録です",
    endDialogTitle = "生産終了・実績確定",
    endDialogIntro = "内容を確認し、生産数を入力して確定してください。",
    productionQty = "生産数",
    btnConfirmEnd = "実績を確定",
    cancel = "キャンセル",
    historyTitle = "本日の確定実績",
    historyProductionQtyTotal = "生産数合計",
    productCd = "製品CD",
    productName = "製品名",
    defectQty = "不良数",
    defectRate = "不良率",
    efficiencyRate = "能率",
    productionStart = "生産開始",
    productionEnd = "生産終了",
    dtWheelMonth = "月",
    dtWheelDay = "日",
    dtWheelHour = "時",
    dtWheelMinute = "分",
    elapsedMinutes = "稼働時間(分)",
    pausedAccumMinutes = "一時停止(分)",
    historyActions = "操作",
    btnEditConfirmed = "編集",
    confirmedEditDialogTitle = "確定実績の修正",
    btnSaveConfirmed = "保存",
    confirmedEditSaved = "確定実績を更新しました",
    cannotEditOthersRecord = "他の溶接作業者の実績は編集できません",
    confirmedEditPauseHint = "一時停止累計は秒単位。稼働は開始・終了・停止から自動計算されます。",
    editTimeRequired = "生産開始・終了の日時を入力してください",
    editTimeOrder = "生産終了は生産開始より後にしてください",
    editPauseTooLong = "一時停止累計は開始〜終了の時間以内にしてください",
    qtyInvalid = "生産数を正しく入力してください",
    remarks = "備考",
)

private val EN = WeldStrings(
    title = "Welding — actual collection",
    helpOpen = "Open operation manual",
    productionDay = "Production date",
    dayPrev = "Previous day",
    dayNext = "Next day",
    dayToday = "Today",
    inspector = "Welder",
    inspectorPlaceholder = "Select welder",
    selectProduct = "Welding product",
    productPlaceholder = "Select welding product",
    productSearchHint = "Search by code or name",
    productListEmpty = "No matching welding products",
    loadProductsFailed = "Failed to load welding products",
    loadPlansFailed = "Failed to load welding plans",
    loadDefectsFailed = "Failed to load defect items",
    saveFailed = "Save failed",
    syncStaleBanner = "Cannot sync with server. Displayed data may be outdated.",
    syncRecovered = "Server sync restored",
    btnRetry = "Reload",
    btnDismiss = "Dismiss",
    networkSslError = "SSL connection failed. Use the backend API URL (e.g. http://LAN-IP:8010/), not the frontend port.",
    networkConnectionError = "Cannot reach the server. Check address, port, and that the backend is running.",
    networkTimeoutError = "Connection timed out. Check your network or try again later.",
    networkServerError = "Server temporarily unavailable. Please try again later.",
    networkNoConnectionError = "No network connection. Check Wi‑Fi or mobile data.",
    offlineModeBanner = "Working offline. Changes are saved on this device and will upload when connected.",
    pendingSyncBanner = "{count} change(s) waiting to sync",
    syncUploadedSuccess = "Offline changes uploaded to the server",
    endProductionSaved = "Production record saved",
    btnScanCode = "Scan",
    scanDialogTitle = "Barcode / QR scan",
    scanDialogHint = "Align the code in the frame. Scan must be 5 digits; matched to welding product CD (5 digits + trailing 1).",
    scanUseFrontCamera = "Front camera",
    scanUseRearCamera = "Rear camera",
    scanRetryCamera = "Start camera",
    scanCameraFailed = "Could not start the camera. Check camera permission.",
    btnScanDialogClose = "Close",
    scanProductInvalidDigits = "Scanned value must be exactly 5 digits",
    scanProductNotFound = "No welding product matches 5-digit code",
    scanProductSelected = "Welding product selected",
    switchProductBlocked = "Cannot change product while production is in progress. End production first.",
    sessionLockedByOtherTerminal = "This production is active on another device. End it on that device first.",
    sessionLockedByOtherTerminalShort = "Other device",
    sessionResumed = "Resumed control on this device. Pause and end are available.",
    sessionRecoveryTitle = "Unfinished welding production",
    sessionRecoveryHint = "Tap Resume to reconnect the timer and controls.",
    btnResumeSession = "Resume work",
    emptySelectProduct = "Select a welding product to start",
    inProgressStripTitle = "In production",
    inProgressStripHint = "Another product is selected. Resume work or end production first.",
    switchedToActiveProduction = "Switched to in-progress product ({label})",
    inspectorAlreadyProducing = "This welder is already producing another product ({label}). End it first.",
    defectTotal = "Defect total",
    elapsed = "Run time",
    pausedAccum = "Pause total",
    timerIdle = "Not started",
    timerRunning = "Running",
    timerPaused = "Paused",
    timerEnded = "Ended",
    btnStart = "Start",
    btnPause = "Pause",
    btnResume = "Resume",
    btnEnd = "End",
    started = "Production started",
    defectByItem = "Defects by type",
    defectHint = "Use +/- after production start",
    attributableProcess = "Attributable process",
    defectItemsEmpty = "No defect items registered",
    endDialogTitle = "End production — confirm",
    endDialogIntro = "Review the summary, enter production quantity, and confirm.",
    productionQty = "Production qty",
    btnConfirmEnd = "Confirm actuals",
    cancel = "Cancel",
    historyTitle = "Today's confirmed records",
    historyProductionQtyTotal = "Production total",
    productCd = "Product CD",
    productName = "Product name",
    defectQty = "Defect qty",
    defectRate = "Defect rate",
    efficiencyRate = "Efficiency",
    productionStart = "Start",
    productionEnd = "End",
    dtWheelMonth = "Mo",
    dtWheelDay = "Day",
    dtWheelHour = "Hr",
    dtWheelMinute = "Min",
    elapsedMinutes = "Run (min)",
    pausedAccumMinutes = "Pause (min)",
    historyActions = "Actions",
    btnEditConfirmed = "Edit",
    confirmedEditDialogTitle = "Edit confirmed record",
    btnSaveConfirmed = "Save",
    confirmedEditSaved = "Confirmed record updated",
    cannotEditOthersRecord = "Cannot edit another welder's record",
    confirmedEditPauseHint = "Pause total is in seconds. Run time is derived from start, end, and pause.",
    editTimeRequired = "Enter production start and end times",
    editTimeOrder = "End time must be after start time",
    editPauseTooLong = "Pause total must not exceed the start–end window",
    qtyInvalid = "Enter a valid production quantity",
    remarks = "Remarks",
)

private val ZH = WeldStrings(
    title = "焊接实绩收集",
    helpOpen = "打开操作说明",
    productionDay = "生产日期",
    dayPrev = "前一天",
    dayNext = "后一天",
    dayToday = "今天",
    inspector = "焊接作业者",
    inspectorPlaceholder = "当前登录用户",
    selectProduct = "焊接产品",
    productPlaceholder = "请选择焊接产品",
    productSearchHint = "按品番/品名搜索",
    productListEmpty = "没有匹配的焊接产品",
    loadProductsFailed = "焊接产品列表加载失败",
    loadPlansFailed = "焊接指示列表加载失败",
    loadDefectsFailed = "不良项目加载失败",
    saveFailed = "保存失败",
    syncStaleBanner = "无法与服务器同步，当前显示的数据可能不是最新。",
    syncRecovered = "已恢复与服务器同步",
    btnRetry = "重新加载",
    btnDismiss = "关闭",
    networkSslError = "SSL 连接失败。请将服务器地址改为后端 API（如 http://局域网IP:8010/），不要使用前端端口 5010。",
    networkConnectionError = "无法连接服务器，请检查地址、端口与后端是否已启动。",
    networkTimeoutError = "连接超时，请检查网络或稍后重试。",
    networkServerError = "服务器暂时不可用，请稍后重试。",
    networkNoConnectionError = "无法连接网络，请检查 Wi‑Fi 或移动数据。",
    offlineModeBanner = "当前离线作业，修改已保存在本机，联网后将自动上传。",
    pendingSyncBanner = "待同步 {count} 项",
    syncUploadedSuccess = "离线数据已上传至服务器",
    endProductionSaved = "实绩已保存",
    btnScanCode = "读取",
    scanDialogTitle = "条形码 / QR 扫描",
    scanDialogHint = "将码对准框内。须为5位数字，与焊接产品CD（末5位+1）匹配。",
    scanUseFrontCamera = "前置摄像头",
    scanUseRearCamera = "后置摄像头",
    scanRetryCamera = "启动摄像头",
    scanCameraFailed = "无法启动摄像头，请检查相机权限。",
    btnScanDialogClose = "关闭",
    scanProductInvalidDigits = "扫描内容必须为5位数字",
    scanProductNotFound = "未找到与5位数字匹配的焊接产品",
    scanProductSelected = "已选择焊接产品",
    switchProductBlocked = "生产中无法更换产品，请先结束生产。",
    sessionLockedByOtherTerminal = "该焊接生产正在其他终端进行，请先在对应终端结束生产。",
    sessionLockedByOtherTerminalShort = "其他终端生产中",
    sessionResumed = "已在本终端恢复操作，可暂停和结束生产。",
    sessionRecoveryTitle = "存在未结束的焊接生产",
    sessionRecoveryHint = "请点击「继续作业」连接计时器和操作。",
    btnResumeSession = "继续作业",
    emptySelectProduct = "选择焊接产品后即可开始作业",
    inProgressStripTitle = "焊接生产中",
    inProgressStripHint = "当前选择了其他产品。请点击「继续作业」，或先结束生产。",
    switchedToActiveProduction = "已切换到正在生产的产品（{label}）",
    inspectorAlreadyProducing = "该焊接作业者正在生产其他产品（{label}），请先结束。",
    defectTotal = "不良合计",
    elapsed = "稼动时间",
    pausedAccum = "暂停累计",
    timerIdle = "未开始",
    timerRunning = "计时中",
    timerPaused = "已暂停",
    timerEnded = "已结束",
    btnStart = "生产开始",
    btnPause = "暂时停止",
    btnResume = "继续",
    btnEnd = "生产结束",
    started = "已开始生产",
    defectByItem = "不良（分项）",
    defectHint = "开始生产后用 +/- 录入",
    attributableProcess = "归属工程",
    defectItemsEmpty = "未登记不良项目",
    endDialogTitle = "生产结束·确定实绩",
    endDialogIntro = "请确认以下内容并输入生产数量后确定。",
    productionQty = "生产数量",
    btnConfirmEnd = "确定实绩",
    cancel = "取消",
    historyTitle = "当日已确定实绩",
    historyProductionQtyTotal = "生产数合计",
    productCd = "产品CD",
    productName = "产品名称",
    defectQty = "不良数",
    defectRate = "不良率",
    efficiencyRate = "能率",
    productionStart = "开始时间",
    productionEnd = "结束时间",
    dtWheelMonth = "月",
    dtWheelDay = "日",
    dtWheelHour = "时",
    dtWheelMinute = "分",
    elapsedMinutes = "稼动时间(分)",
    pausedAccumMinutes = "暂停(分)",
    historyActions = "操作",
    btnEditConfirmed = "编辑",
    confirmedEditDialogTitle = "修改确定实绩",
    btnSaveConfirmed = "保存",
    confirmedEditSaved = "已更新确定实绩",
    cannotEditOthersRecord = "无法编辑其他焊接作业者的实绩",
    confirmedEditPauseHint = "暂停累计单位为秒。稼动时间由开始、结束与暂停自动计算。",
    editTimeRequired = "请输入生产开始与结束时间",
    editTimeOrder = "结束时间须晚于开始时间",
    editPauseTooLong = "暂停累计不能超过开始至结束的时间范围",
    qtyInvalid = "请输入正确的生产数量",
    remarks = "备注",
)

private val VI = WeldStrings(
    title = "Thu thập thực tế hàn",
    helpOpen = "Mở hướng dẫn vận hành",
    productionDay = "Ngày sản xuất",
    dayPrev = "Ngày trước",
    dayNext = "Ngày sau",
    dayToday = "Hôm nay",
    inspector = "Người hàn",
    inspectorPlaceholder = "Chọn người kiểm tra",
    selectProduct = "Sản phẩm hàn",
    productPlaceholder = "Chọn sản phẩm kiểm tra",
    productSearchHint = "Tìm theo mã hoặc tên",
    productListEmpty = "Không có sản phẩm kiểm tra phù hợp",
    loadProductsFailed = "Không tải được danh sách sản phẩm kiểm tra",
    loadPlansFailed = "Không tải được danh sách chỉ thị hàn",
    loadDefectsFailed = "Không tải được hạng mục lỗi",
    saveFailed = "Lưu thất bại",
    syncStaleBanner = "Không đồng bộ được với máy chủ. Dữ liệu hiển thị có thể chưa cập nhật.",
    syncRecovered = "Đã khôi phục đồng bộ với máy chủ",
    btnRetry = "Tải lại",
    btnDismiss = "Đóng",
    networkSslError = "Kết nối SSL thất bại. Hãy dùng URL API backend (vd. http://LAN-IP:8010/), không dùng cổng frontend.",
    networkConnectionError = "Không kết nối được máy chủ. Kiểm tra địa chỉ, cổng và backend đã chạy chưa.",
    networkTimeoutError = "Hết thời gian kết nối. Kiểm tra mạng hoặc thử lại sau.",
    networkServerError = "Máy chủ tạm thời không khả dụng. Vui lòng thử lại sau.",
    networkNoConnectionError = "Không có kết nối mạng. Kiểm tra Wi‑Fi hoặc dữ liệu di động.",
    offlineModeBanner = "Đang làm việc ngoại tuyến. Thay đổi được lưu trên thiết bị và sẽ tự tải lên khi có mạng.",
    pendingSyncBanner = "{count} thay đổi chờ đồng bộ",
    syncUploadedSuccess = "Đã tải lên thay đổi ngoại tuyến lên máy chủ",
    endProductionSaved = "Đã lưu thực tế sản xuất",
    btnScanCode = "Đọc",
    scanDialogTitle = "Quét mã vạch / QR",
    scanDialogHint = "Căn mã trong khung. Phải đúng 5 chữ số; khớp CD sản phẩm kiểm tra (5 số + hậu tố 1).",
    scanUseFrontCamera = "Camera trước",
    scanUseRearCamera = "Camera sau",
    scanRetryCamera = "Bật camera",
    scanCameraFailed = "Không bật được camera. Kiểm tra quyền camera.",
    btnScanDialogClose = "Đóng",
    scanProductInvalidDigits = "Mã quét phải đúng 5 chữ số",
    scanProductNotFound = "Không có sản phẩm kiểm tra khớp 5 chữ số",
    scanProductSelected = "Đã chọn sản phẩm kiểm tra",
    switchProductBlocked = "Không đổi sản phẩm khi đang sản xuất. Hãy kết thúc trước.",
    sessionLockedByOtherTerminal = "Sản xuất này đang chạy trên thiết bị khác. Hãy kết thúc trên thiết bị đó trước.",
    sessionLockedByOtherTerminalShort = "Thiết bị khác",
    sessionResumed = "Đã tiếp tục điều khiển trên thiết bị này. Có thể tạm dừng và kết thúc.",
    sessionRecoveryTitle = "Còn sản xuất hàn chưa kết thúc",
    sessionRecoveryHint = "Nhấn Tiếp tục để kết nối bộ đếm và thao tác.",
    btnResumeSession = "Tiếp tục công việc",
    emptySelectProduct = "Chọn sản phẩm kiểm tra để bắt đầu",
    inProgressStripTitle = "Đang sản xuất",
    inProgressStripHint = "Đang chọn sản phẩm khác. Nhấn Tiếp tục hoặc kết thúc sản xuất trước.",
    switchedToActiveProduction = "Đã chuyển sang sản phẩm đang SX ({label})",
    inspectorAlreadyProducing = "Kiểm tra viên đang sản xuất sản phẩm khác ({label}). Hãy kết thúc trước.",
    defectTotal = "Tổng lỗi",
    elapsed = "Thời gian chạy",
    pausedAccum = "Tạm dừng",
    timerIdle = "Chưa bắt đầu",
    timerRunning = "Đang đo",
    timerPaused = "Đang tạm dừng",
    timerEnded = "Đã kết thúc",
    btnStart = "Bắt đầu",
    btnPause = "Tạm dừng",
    btnResume = "Tiếp tục",
    btnEnd = "Kết thúc",
    started = "Đã bắt đầu sản xuất",
    defectByItem = "Lỗi theo hạng mục",
    defectHint = "Dùng +/- sau khi bắt đầu sản xuất",
    attributableProcess = "Công đoạn thuộc",
    defectItemsEmpty = "Chưa đăng ký hạng mục lỗi",
    endDialogTitle = "Kết thúc — xác nhận",
    endDialogIntro = "Kiểm tra nội dung, nhập số lượng sản xuất và xác nhận.",
    productionQty = "Số lượng SX",
    btnConfirmEnd = "Xác nhận thực tế",
    cancel = "Hủy",
    historyTitle = "Thực tế đã xác nhận hôm nay",
    historyProductionQtyTotal = "Tổng số lượng SX",
    productCd = "Mã SP",
    productName = "Tên sản phẩm",
    defectQty = "Số lỗi",
    defectRate = "Tỷ lệ lỗi",
    efficiencyRate = "Năng suất",
    productionStart = "Bắt đầu",
    productionEnd = "Kết thúc",
    dtWheelMonth = "Th",
    dtWheelDay = "Ng",
    dtWheelHour = "G",
    dtWheelMinute = "P",
    elapsedMinutes = "TG chạy (phút)",
    pausedAccumMinutes = "Tạm dừng (phút)",
    historyActions = "Thao tác",
    btnEditConfirmed = "Sửa",
    confirmedEditDialogTitle = "Sửa thực tế đã xác nhận",
    btnSaveConfirmed = "Lưu",
    confirmedEditSaved = "Đã cập nhật thực tế xác nhận",
    cannotEditOthersRecord = "Không thể sửa bản ghi của người kiểm tra khác",
    confirmedEditPauseHint = "Tổng tạm dừng tính bằng giây. Thời gian chạy được tính từ bắt đầu, kết thúc và tạm dừng.",
    editTimeRequired = "Nhập thời gian bắt đầu và kết thúc sản xuất",
    editTimeOrder = "Thời gian kết thúc phải sau thời gian bắt đầu",
    editPauseTooLong = "Tổng tạm dừng không được vượt quá khoảng bắt đầu–kết thúc",
    qtyInvalid = "Nhập số lượng sản xuất hợp lệ",
    remarks = "Ghi chú",
)

fun weldStringsFor(locale: WeldLocale): WeldStrings = when (locale) {
    WeldLocale.Ja -> JA
    WeldLocale.En -> EN
    WeldLocale.Zh -> ZH
    WeldLocale.Vi -> VI
}

fun WeldStrings.networkErrorHints(): NetworkErrorHints = NetworkErrorHints(
    ssl = networkSslError,
    connection = networkConnectionError,
    timeout = networkTimeoutError,
    server = networkServerError,
    noConnection = networkNoConnectionError,
)
